---
title: "Immunarch 0.9.x -> 1.0.0 Migration Guide"
date: "support@immunomind.com"
output:
  html_document:
    fig_height: 8
    fig_width: 10
    theme: spacelab
    toc: yes
  pdf_document:
    toc: yes
  word_document:
    toc: yes
---


<!--
%\VignetteEngine{knitr::rmarkdown}
%\VignetteIndexEntry{Immunarch 0.9.x -> 1.0.0 Migration Guide}
%\VignettePackage{immunarch}
-->

# Overview

There are three major points related to transformations: 

- how immunarch 1.0.0 works with data,
- interface or API, i.e., names and parameters of the functions, implemented in immunarch, and
- removing or moving some functions to separate package to make immunarch easier to install and manage

For more long-term plans take a look at the final sections.

For the nearest changes, please continue reading.


# Major update for the current version: Spring 2025

## What changed and what you can do

removed ggpubr, factoextra, fpc, ggraph, phangorn, igraph and some other packages
Sadly I didn't have a chance to do it gradually due to the CRAN requirements.
The good news is that immunarch now needs *only* around 80 packages to install instead of 184 before.

If you have been using immunarch for some time, there won't be anything changing for you.

If you want to re-install immunarch, you may encounter errors that asks you to install some of the packages. Just install it, and the function will work - nothing else was changed.


# Next major update: Summer 2025

## What will be changed

## What can you do to mitigate risks


# Future major updates: Autumn-Winter 2025

## What will be changed

## What can you do to mitigate risks


# How immunarch 1.0.0. would look like

Why do we need even need it?

- outdated code, hard to support and maintain
- imrpoving the code culture in academia

## Scalable and fast data processing

## Lighter interface

## Modularizing the ecosystem



```{r setup, include=FALSE, echo=FALSE}
# knitr::knit_hooks$set(optipng = knitr::hook_optipng)
# knitr::opts_chunk$set(optipng = '-o7')

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.align = "center")
knitr::opts_chunk$set(fig.width = 12)
knitr::opts_chunk$set(fig.height = 6)

library(immunarch)
# source("../R/testing.R")
# immdata = load_test_data()
data(immdata)
```
