# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fill_vec <- function(read_vec, read_indices) {
    .Call(`_immunarch_fill_vec`, read_vec, read_indices)
}

fill_reads <- function(new_reads, new_counts) {
    .Call(`_immunarch_fill_reads`, new_reads, new_counts)
}

